# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cddeec6bb668b1e02b2625fb3fc64cee47748517465404669b01b5a7ebbf6084bf0d5780c8def884700ac6c3f0651367772932dd4b39dd7bb6e612cfb50b3cb

test:
  secret_key_base: 896bf325b43c40e47e94ef4ef5515289471ed564e0558108df8565b9f36956d76511e83559f88f607589ae865ef18442e3cdf6b08a49e2299be3022cb9e24dd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
